### ISSUE TITLE
Better Save support

### ISSUE THREAD

**Issue by alehandrof** [facelessuser/FuzzyFileNav#19]
I would like FuzzyNav to replace the Save / Save As... commands. Either by replacing the `save` the and `prompt_save_as` commands in the user's bindings or by creating something that kicks in `on_pre_save`. In any case it would run something like this:

- Save
	- If file exists, save.
	- If file is new, popup FuzzyNav, filled in with contents of first line (up to a certain number of characters, probably) + default syntax extension (if other than Plain Text)
- Save As
	- Popup FuzzyNav, filled in with current name, or as above if unsaved

I suspect there may be trouble with overwriting files, etc.But  I am quite happy to be a guinea pig, though.

**Comment by facelessuser** [comment]
I think it has become clear at this point that no further work has been done on this.  I guess it is obvious I have no intentions to finish this at this point.  I am closing this feature and passing on it.

**Comment by alehandrof** [comment]
No problem. Thanks for all your work on Sublime plugins. FuzzyFileNav is still one of my must-haves :)
