### ISSUE TITLE
Open folder instead of file?

### ISSUE THREAD

**Issue by lawrence-berry** [facelessuser/FuzzyFileNav#24]
Mayv'e just missed this feature in the docs but is it possible to open an entire folder instead of an individual file using this plugin? I think ideally holding shift when selecting an option in the context menu would open the folder rather than descending into it. Great plugin btw, nice to have file browsing integrated with the context menu in this way.

**Comment by facelessuser** [comment]
Can you elaborate?  There already is a command to add a folder to the project:

For OSX:

```js
    {
        "keys": ["super+p"],
        "command": "fuzzy_open_folder",
        "context": [{"key": "fuzzy_open_folder"}]
    },
```

`ctrl+p` for windows and nix.

**Comment by facelessuser** [comment]
As I haven't heard anything else, I assume I answered your question.
