### ISSUE TITLE
Feature Request.

### ISSUE THREAD

**Issue by ctf0** [facelessuser/FuzzyFileNav#25]
Hi there, many thanx for this plugin, i had a couple of ideas and i thought it may help make the plugin even more helpful.

- from all the shortcuts that the plugin use i can only `create new file & create new folder` and thats mostly because all the other shortcuts have a native function in ST ,like `super+d, super+v, etc...`  
so is there away to make the plugin "disable/override" the default keybinding when its active and "re-enable/di-override" when its closed ? ,
this way u don't need to make anew keybinding and u get to use the same shortcuts whether u were editing a text or manipulating a file.

- am more than thankful for the context-menu options to activate FFS but imho the main reason that anyone would love this plugin is that u get to use ur keyboard to do everything and having to activate the plugin only by mouse is kinda counter-intuitive, so can we also use the quick-panle to activate FFS as-well ?

**Comment by facelessuser** [comment]
> from all the shortcuts that the plugin use i can only create new file & create new folder and thats mostly because all the other shortcuts have a native function in ST ,like super+d, super+v, etc...

> so is there away to make the plugin "disable/override" the default keybinding when its active and "re-enable/di-override" when its closed ? ,
this way u don't need to make anew keybinding and u get to use the same shortcuts whether u were editing a text or manipulating a file.

I guess I am confused.  The current implementation of the shortcuts only work when the fuzzy panel is open.  They use contexts keys to make sure that the right conditions are met before they swallow the shortcut.  If the conditions are not met, it passes the shortcut on to be used by some other plugin.

> am more than thankful for the context-menu options to activate FFS but imho the main reason that anyone would love this plugin is that u get to use ur keyboard to do everything and having to activate the plugin only by mouse is kinda counter-intuitive, so can we also use the quick-panle to activate FFS as-well ?

Don't see why not.  I guess I always figured people would just bind it to a shortcut.  I personally override the file open shortcut:

```js
    //////////////////////////////////
    // Fuzzy File Nav
    //////////////////////////////////
    // Windows
    { "keys": ["ctrl+o"], "command": "fuzzy_start_from_file" },
    { "keys": ["ctrl+shift+o"], "command": "fuzzy_bookmarks_load" },
```
But adding it to the palette seems fine too.

**Comment by ctf0** [comment]
for the first issue
some of ST shortcuts are modified check below
```
{ "keys": ["super+v"], "command": "paste_and_indent" },
{ "keys": ["super+c"], "command": "noop", "context":
     [
         { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
         { "key": "preceding_text", "operator": "regex_match", "operand": "^\\s*$", "match_all": true },
         { "key": "following_text", "operator": "regex_match", "operand": "^\\s*$", "match_all": true }
     ]
},
{ "keys": ["super+x"], "command": "noop", "context":
     [
         { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
         { "key": "preceding_text", "operator": "regex_match", "operand": "^\\s*$", "match_all": true },
         { "key": "following_text", "operator": "regex_match", "operand": "^\\s*$", "match_all": true }
     ]
},
{ "keys": ["super+d"], "command": "duplicate_line" },
```
so maybe thats why the functions from this plugin doesnt work ?

**Comment by facelessuser** [comment]
Maybe you are confused on how to use the feature.  For instance.  If you want to copy a file you can navigate to the file and press `tab` to get the full file name, then press `super + c` to copy.  If you press `super + c` without the files full name in the input box, it will default to a normal text copy.  Once the fuzzy  nav clipboard has an item in it, when you are in the folder you want, you can press `super + v`.

File delete is the same.  Select file or start typing and then press `tab` to get the full file name.  Then press `super + d` to delete.

**Comment by facelessuser** [comment]
Looks like I did document the behavior.  It requries the full name in the input box: https://github.com/facelessuser/FuzzyFileNav#fuzzy-file-delete

> ### Fuzzy File Delete
> `ctrl+d` Deletes the folder/file object currently typed (full name) in the Fuzzy File Nav panel.

**Comment by ctf0** [comment]
well thats what is driving me nuts ,i can copy but i cant paste ,instead if have a copied text when i use `super+v` i get the pasted text instead and not the file i copied.

if i tried to delete a file ,it doesnt work instead the Edit menu flash ,which means its tryin to invoke the `duplicate_line` cmnd and not the plugin cmnd which is `delete file`

**Comment by facelessuser** [comment]
I am not sure what OS you are using, but on OSX, `shift+super+d` is `duplicate_line`.

All of my examples in this thread are currently for OSX.  It seems to be working fine for me, but I **must** `tab` to get the full file name, then `super + c` and `super + v` works.  Same with `delete`.

**Comment by ctf0** [comment]
am on OSX 10.9.5 ,but its not working for some reason :( .anyway i don't want to take more of ur time ,still thanx for ur help.

**Comment by ctf0** [comment]
i found the solution incase someone else ran into that ,

ST cant have the same shortcut to be overridden 2 times, so if u have a shortcut in the user keybinding file and there was some plugin that uses the same shortcut ST will simply be ignores it.

so for that u either remove ur modified shortcuts or copy the `Default (OS?).sublime-keymap` to `Packages/Default` and add ur modifications in there ,now the plugin will get to work and ur modified shortcuts will also work.

**Comment by facelessuser** [comment]
This is correct.  If a shortcut executes, it tells sublime the shortcut was handled and sublime stops processing the command to avoid weird behavior.  That is why using context is important.  FFN doesn't want to override the default except when the conditions are right, but FFN can't necessarily control which overrides sublime tries first.  In your case, both you and FFN tried to override the shortcut, so sublime must be trying yours before FFN.  I think things in Default are always tried last.
