### ISSUE TITLE
fuzzy_get_cwd is called each second if Nav quick panel is open

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/FuzzyFileNav#30]
Just found by luck the `fuzzy_get_cwd` command being called each second after calling `fuzzy_start_from_file {"paths": []}` even while doing nothing. Is this required for something?

**Comment by facelessuser** [comment]
I'm displaying the status globally (not per view).  So the API for the global status times out and erases the status.  So I keep refreshing it.  When the session is done, we no longer update it, and then sublime auto clears it.  I think I did it so I didn't have to clean up all the view status messages if the active view kept changing cause you were doing stuff in FuzzyFileNav.

**Comment by deathaxe** [comment]
Ah, there is a status message. Did realize it yet. So it's intended behavior, ok.

**Comment by deathaxe** [comment]
I am convinced of the quality of your plugins. 😉
