### ISSUE TITLE
[feature] open a folder in new window

### ISSUE THREAD

**Issue by rchl** [facelessuser/FuzzyFileNav#37]
It would be useful if it would be possible to open a whole folder in a new window from the file nav.

I think in ST4 it should be possible because I think it's possible to trigger actions while holding key modifiers. Not 100% sure though.

**Comment by facelessuser** [comment]
Yeah, adding a folder is certainly doable. I'd have to experiment, mechanics of modifiers and, such. I do need to spend some time on this project some time soon.

**Comment by facelessuser** [comment]
This should be possible in the new version when it releases. `primary+p` adds a folder to the current window, but `primary+shift+p` will add it to a new window.

I'm working to get it ready for release. It is possible I'll get it out this weekend.
