### ISSUE TITLE
Get new version out

### ISSUE THREAD

**Issue by facelessuser** [facelessuser/FuzzyFileNav#39]
Been pretty busy, but we need to just double-check `master` and make sure it is ready for release.

**Comment by thezimmee** [comment]
@facelessuser I love this plugin for navigating files, thanks for creating it! Any update on getting this new version out?

**Comment by facelessuser** [comment]
Yeah, I can revisit this. I support a lot of repos, so when one goes quiet, I sometimes forget that there are some changes to get out.

**Comment by thezimmee** [comment]
No problem. Thanks for supporting all the repos! I'm not great at Python but happy to help if/where I can...

**Comment by facelessuser** [comment]
I'm going to get this out over this weekend. This is now top of my list.

**Comment by facelessuser** [comment]
Done. It will take some time for Package Control to see it though.
