### ISSUE TITLE
Add option to load files from folder recursively

### ISSUE THREAD

**Issue by ryuukk** [facelessuser/FuzzyFileNav#40]
Sublime Text developpers are stubborn and they don't want to add a way to disable the automatic file preview

Your addon seems to let me search for files without the preview, so that's great

However it only searches for files in a folder, it would be cool to be able to have an option that lets me load files recursively

Example:

```
Fuzzy File Nav -> Fuzzy Projects Folder
    -> opens the popup
    -> load files recursively
```

Doing that everytime i open the menu would waste too much ressources

So i suggest doing the extra mile and cache the result and only update the cache on new_file/file_removed events, if that's a thing in sublime text api

Thanks for this addon, it transforms sublime text from useless to usable

**Comment by FichteFoll** [comment]
> So i suggest doing the extra mile and cache the result and only update the cache on new_file/file_removed events, if that's a thing in sublime text api

 It's not.

> How to get the full path of the folder on line 388

That's what lines 394 and 397 already do.

> How to load files recursively with python

`os.walk`

**Comment by facelessuser** [comment]
This project is meant to allow navigation of the file system, not to index an entire project or folder and then search it. This request is fundamentally different from what this project aims to do.

While I think something that does what you request is a fine idea, it is out of scope of this project's goals.  I've certainly written personal plugins (not publicly available) that allow me to glob the file system, but I also wouldn't add that here as it is out of scope for this project as well.

**Comment by facelessuser** [comment]
https://gist.github.com/facelessuser/c7722e552f47965bbe524b6ebbaba46f

You will have to manually install it. I have not made a public repo, just the gist found above. You can turn off previews by removing the code related to them from the script if desired. Please reference the `wcmatch` library documentation in the readme to better understand the supported glob features and such.

**Comment by facelessuser** [comment]
I'm assuming the question was answered. I will be closing this for now.
