### ISSUE TITLE
Cannot copy file error on Windows

### ISSUE THREAD

**Issue by polyscone** [facelessuser/FuzzyFileNav#43]
It seems like this bug may have existed for a long time, but only showed up when the package was updated on my machine a few weeks ago.

I've not sure exactly which version I had before it updated, but from the looks of the commit history I was running on a version that existed before this commit 87fd4724026e7c70eed1036d48462a566b60a0ed.

The problem is that when I copy a file and try to paste it somewhere and exception is thrown with the message:

> [WinError 2] The system cannot find the file specified: <destination path here>

As can be seen from the diff in the commit linked above, the problem is this line:
https://github.com/facelessuser/FuzzyFileNav/blob/master/fuzzy_file_nav.py#L582

Since the destination path doesn't exist yet `os.path.samefile` throws and prevents the copy from happening.
I don't use Python, and don't know how you want to deal with it, but changing the line to this fixed it for me:
```py
same = path.samefile(self.from_path, path.dirname(self.to_path))
```

The same problem appears when copying directories too, which is the same problem from this line:
https://github.com/facelessuser/FuzzyFileNav/blob/master/fuzzy_file_nav.py#L544

As an aside, I also noticed that `format` is typo'd as `fromat` here too:
https://github.com/facelessuser/FuzzyFileNav/blob/master/fuzzy_file_nav.py#L587-L590

If the fix is just as I described would you like me to open a PR?

**Comment by facelessuser** [comment]
The change was made a while ago, but never released. `samefile` checks for existence. So, I need to rework the code a bit. I'll take a look.

**Comment by facelessuser** [comment]
I've tagged a release, it should be available whenever package control syncs up (maybe an hour or two)

**Comment by polyscone** [comment]
Ah ok, that makes sense.

Thanks for the quick reply and PR, I appreciate it.
